/* This is file is automatically generated */
#define BUILD_ARCH "win32"
#define BUILD_NODE "EC-WIN7-X64-01"
#define COMPILER "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe"
#define COMPILERVERS ""
#define  MAKESHAREDLIB "cl $Opt -nologo -TP -c -nologo -IC:/build/workspace/root-release-5.34/BUILDTYPE/Release/COMPILER/vc12/LABEL/win7/sources/root_v5.34.38/root/build/win -FIw32pragma.h -FIsehmap.h -MD -GR -EHsc- -W3 -wd4244 -D_WIN32 /MP  $IncludePath $SourceFiles -Fo$ObjectFiles && bindexplib $LibName $ObjectFiles > $BuildDir\\$LibName.def && lib -nologo -MACHINE:IX86 -out:$BuildDir\\$LibName.lib $ObjectFiles -def:$BuildDir\\$LibName.def && link -nologo $ObjectFiles -DLL -out:$BuildDir\\$LibName.dll $BuildDir\\$LibName.exp -LIBPATH:%ROOTSYS%\\lib  $LinkedLibs libCore.lib libCint.lib kernel32.lib advapi32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib && if EXIST \"$BuildDir\\$LibName.dll.manifest\" ( mt -nologo -manifest \"$BuildDir\\$LibName.dll.manifest\" \"-outputresource:$BuildDir\\$LibName.dll;2\" && del \"$BuildDir\\$LibName.dll.manifest\" )"
#define MAKEEXE "cl -nologo -TP -Iinclude -I../include -c $Opt -nologo -IC:/build/workspace/root-release-5.34/BUILDTYPE/Release/COMPILER/vc12/LABEL/win7/sources/root_v5.34.38/root/build/win -FIw32pragma.h -FIsehmap.h -MD -GR -EHsc- -W3 -wd4244 -D_WIN32 /MP  $IncludePath $SourceFiles && link -opt:ref  $ObjectFiles $LinkedLibs advapi32.lib -out:$ExeName  && if EXIST \"$ExeName.exe.manifest\" ( mt -nologo -manifest \"$ExeName.exe.manifest\" \"-outputresource:$ExeName.exe;1\" && del \"$ExeName.exe.manifest\" )"
#define CXXOPT "-O2"
#define CXXDEBUG "-Z7"
#define ROOTBUILD "debug"
#define LINKEDLIBS "-LIBPATH:%ROOTSYS% lib/libCore.lib lib/libCint.lib lib/libRint.lib "
#define INCLUDEPATH "-I%ROOTSYS%/include"
#define OBJEXT "obj"
#define SOEXT "dll" 
