# -*- mode: makefile -*-
#
# Makefile definitions included by the top Makefile

# The macro below is expanded when 'realpath' is not built-in.
# Built-in 'realpath' is available on GNU Make 3.81.
realpath = $(shell cd $(1); pwd)

ROOT_SRCDIR    := $(call realpath, C:/build/workspace/root-release-5.34/BUILDTYPE/Release/COMPILER/vc12/LABEL/win7/sources/root_v5.34.38/root)
ROOT_OBJDIR    := $(call realpath, C:/build/workspace/root-release-5.34/BUILDTYPE/Release/COMPILER/vc12/LABEL/win7/build/root_v5.34.38-cmake)

ifndef ROOT_SRCDIR
$(error Error determining ROOT_SRCDIR)
endif
ifndef ROOT_OBJDIR
$(error Error determining ROOT_OBJDIR)
endif

# The macro below strips off the source dir path to make a relative path name
stripsrc = $(subst $(ROOT_SRCDIR)/,,$(1))

ARCH           := win32
HOST           := 

USECONFIG      := FALSE
MKLIBOPTIONS   := -v 5 34 38 

EXTRA_CFLAGS   := -Iinclude -nologo -IC:/build/workspace/root-release-5.34/BUILDTYPE/Release/COMPILER/vc12/LABEL/win7/sources/root_v5.34.38/root/build/win -FIw32pragma.h -FIsehmap.h -MD -GR -EHsc- -W3 -wd4244 -D_WIN32 /MP 
USERCONF_CFLAGS:= 
EXTRA_CXXFLAGS := -Iinclude -nologo -IC:/build/workspace/root-release-5.34/BUILDTYPE/Release/COMPILER/vc12/LABEL/win7/sources/root_v5.34.38/root/build/win -FIw32pragma.h -FIsehmap.h -MD -GR -EHsc- -W3 -wd4244 -D_WIN32 /MP 
USERCONF_CXXFLAGS:= 
EXTRA_LDFLAGS  := 
WERROR         := 
WINRTDEBUG     := no

GLBPATCHFLAGS  := 
EXTRA_AUTHFLAGS:=    

BINDIR         := $(ROOTSYS)/bin
LIBDIR         := $(ROOTSYS)/lib
INCDIR         := $(ROOTSYS)/include
ETCDIR         := $(ROOTSYS)/etc
MANDIR         := $(ROOTSYS)/man
DATADIR        := $(ROOTSYS)/.
ELISPDIR       := $(ROOTSYS)/emacs/site-lisp
TTFFONTDIR     := $(ROOTSYS)/fonts
MACRODIR       := $(ROOTSYS)/macros
SRCDIR         := $(ROOTSYS)/src
ICONPATH       := $(ROOTSYS)/icons
CINTINCDIR     := $(ROOTSYS)/cint
DOCDIR         := $(ROOTSYS)/.
TESTDIR        := $(ROOTSYS)/test
TUTDIR         := $(ROOTSYS)/tutorials
ACLOCALDIR     := $(ROOTSYS)/aclocal

BUILDX11       := no
X11INCDIR      := $(filter-out /usr/include, )
X11LIBDIR      := -L
XPMLIBDIR      := -L
XPMLIB         := 
XFTLIB         := no

BUILDCOCOA     := 
MACOSXVERS     := 
OSXSDK         := 
IOSVERS        := 
IOSSDK         := 

CXX11          := 
CXX14          := 
LIBCXX         := 

EXPLICITLINK   := yes

ENABLETHREAD   := yes
OSTHREADFLAG   := 
OSTHREADLIBDIR := 
OSTHREADLIB    := 

BUILTINFREETYPE:= yes

BUILTINPCRE    := yes

BUILTINZLIB    := yes
ZLIBLIBDIR     := 
ZLIBCLILIB     := 
ZLIBINCDIR     := $(filter-out /usr/include, ZLIB_INCLUDE_DIR-NOTFOUND)

BUILTINLZMA    := 
LZMALIBDIR     := 
LZMACLILIB     := 
LZMAINCDIR     := $(filter-out /usr/include, )

BUILTINLZ4     := 
LZ4LIBDIR      := 
LZ4CLILIB      := 
LZ4INCDIR      := $(filter-out /usr/include, )

BUILDGL        := yes
OPENGLLIBDIR   := 
OPENGLULIB     := glu32
OPENGLLIB      := opengl32
OPENGLINCDIR   := $(filter-out /usr/include, )

BUILDLDAP      := no
LDAPLIBDIR     := 
LDAPCLILIB     := LDAP_LIBRARY-NOTFOUND
LDAPINCDIR     := $(filter-out /usr/include, LDAP_INCLUDE_DIR-NOTFOUND)

BUILDMYSQL     := no
MYSQLLIBDIR    := 
MYSQLCLILIB    := MYSQL_LIBRARY-NOTFOUND
MYSQLINCDIR    := $(filter-out /usr/include, MYSQL_INCLUDE_DIR-NOTFOUND)

BUILDORACLE    := no
ORACLELIBDIR   := 
ORACLECLILIB   := ORACLE_LIBRARY_OCCI-NOTFOUND ORACLE_LIBRARY_CLNTSH-NOTFOUND ORACLE_LIBRARY_LNNZ-NOTFOUND
ORACLEINCDIR   := $(filter-out /usr/include, ORACLE_INCLUDE_DIR-NOTFOUND)

BUILDPGSQL     := no
PGSQLLIBDIR    := 
PGSQLCLILIB    := 
PGSQLINCDIR    := $(filter-out /usr/include, )

BUILDSQLITE     := no
SQLITELIBDIR    := 
SQLITECLILIB    := 
SQLITEINCDIR    := $(filter-out /usr/include, SQLITE_INCLUDE_DIR-NOTFOUND)

BUILDSAPDB     := no
SAPDBLIBDIR    := 
SAPDBCLILIB    := 
SAPDBINCDIR    := $(filter-out /usr/include, )

BUILDODBC      := no
ODBCLIBDIR     := 
ODBCCLILIB     := 
ODBCINCDIR     := $(filter-out /usr/include, )

BUILDQT        := no
BUILDQTGSI     := 
QTLIBDIR       := 
QTLIB          := 
QTINCDIR       := $(filter-out /usr/include, )
QTVERS	       := 
QTMOCEXE       := 

BUILDRFIO      := no
SHIFTLIBDIR    := 
SHIFTLIB       := 
SHIFTINCDIR    := $(filter-out /usr/include, )
SHIFTCFLAGS    := 

BUILDCASTOR    := no
CASTORLIBDIR   := 
CASTORCLILIB   := 
CASTORINCDIR   := $(filter-out /usr/include, CASTOR_INCLUDE_DIR-NOTFOUND)
CASTORCFLAGS   := 

BUILDDAVIX      := no
DAVIXLIBDIR     := 
DAVIXCLILIB     := 
DAVIXINCDIR     := $(filter-out /usr/include, )

BUILDDCAP      := 
DCAPLIBDIR     := 
DCAPLIB        := DCAP_LIBRARY-NOTFOUND
DCAPINCDIR     := $(filter-out /usr/include, DCAP_INCLUDE_DIR-NOTFOUND)

BUILDFTGL      := yes
FTGLLIBDIR     := 
FTGLLIBS       := FTGL
FTGLINCDIR     := $(filter-out /usr/include, C:/build/workspace/root-release-5.34/BUILDTYPE/Release/COMPILER/vc12/LABEL/win7/sources/root_v5.34.38/root/graf3d/ftgl/inc)
ifeq ($(BUILDFTGL), yes)
FTGLCPPFLAGS   := -DBUILTIN_FTGL
endif

BUILDGLEW      := yes
GLEWLIBDIR     := 
GLEWLIBS       := 
GLEWINCDIR     := $(filter-out /usr/include, )
ifeq ($(BUILDGLEW), yes)
GLEWCPPFLAGS   := -DBUILTIN_GLEW
endif

BUILDGFAL      := no
GFALLIBDIR     := 
GFALCLILIB     := GFAL_LIBRARY-NOTFOUND
GFALINCDIR     := $(filter-out /usr/include, GFAL_INCLUDE_DIR-NOTFOUND)
SRMIFCEINCDIR  := $(filter-out /usr/include, )
GLIB2INCDIR    := $(filter-out /usr/include, )

BUILDGLITE     := no
GLITELIBDIR    := 
GAWLIB         := 
GAW_CPPFLAGS   := $(filter-out /usr/include, )

BUILDMEMSTAT   := no

BUILDBONJOUR   := no
DNSSDLIBDIR    := 
DNSSDLIB       := BONJOUR_LIBRARY-NOTFOUND
DNSSDINCDIR    := $(filter-out /usr/include, )
BONJOURCPPFLAGS := 

BUILDCHIRP     := no
CHIRPLIBDIR    := 
CHIRPCLILIB    := 
CHIRPINCDIR    := $(filter-out /usr/include, )

BUILDHDFS      := no
HDFSLIBDIR     := 
HDFSCLILIB     := 
HDFSINCDIR     := $(filter-out /usr/include, )
JNIINCDIR      := $(filter-out /usr/include, ) $(filter-out /usr/include, /linux)
JVMCLILIB      := 
JVMLIBDIR      := 

BUILDALIEN     := no
ALIENLIBDIR    := 
ALIENCLILIB    := ALIEN_LIBRARY-NOTFOUND
ALIENINCDIR    := $(filter-out /usr/include, ALIEN_INCLUDE_DIR-NOTFOUND)

BUILDASIMAGE   := yes
BUILTINASIMAGE := ON
ASEXTRALIB     := 
ASEXTRALIBDIR  := 
ASJPEGINCDIR   := $(filter-out /usr/include, JPEG_INCLUDE_DIR-NOTFOUND)
ASPNGINCDIR    := $(filter-out /usr/include, )
ASTIFFINCDIR   := $(filter-out /usr/include, TIFF_INCLUDE_DIR-NOTFOUND)
ASINCDIR       := $(filter-out /usr/include, )
ASLIB          := 
ASLIBDIR       := 

BUILDFPYTHIA6    := no
FPYTHIA6LIBDIR   := 
FPYTHIA6LIB      := PYTHIA6_LIBRARY-NOTFOUND
FPYTHIA6CPPFLAGS := 

BUILDFPYTHIA8    := yes
FPYTHIA8INCDIR   := $(filter-out /usr/include, )
FPYTHIA8LIBDIR   := 
FPYTHIA8LIB      := C:/external/vc12/pythia8/lib/Release/libPythia8.lib

BUILDFFTW3     := no
FFTW3LIBDIR    := 
FFTW3LIB       := FFTW_LIBRARY-NOTFOUND
FFTW3INCDIR    := $(filter-out /usr/include, FFTW_INCLUDE_DIR-NOTFOUND)

BUILDFITSIO    := no
CFITSIOLIBDIR  := 
CFITSIOLIB     := 
CFITSIOINCDIR  := $(filter-out /usr/include, )

BUILDGVIZ      := no
GRAPHVIZLIBDIR := 
GRAPHVIZLIB    := 
GRAPHVIZINCDIR := $(filter-out /usr/include, )
GRAPHVIZCFLAGS := 

BUILDPYTHON    := yes
PYTHONLIBDIR   := 
PYTHONLIB      := C:/external/Python27/libs/python27.lib
PYTHONINCDIR   := $(filter-out /usr/include, C:/external/Python27/include)
PYTHONLIBFLAGS := 

BUILDRUBY      := no
RUBYLIBDIR     := 
RUBYLIB        := 
RUBYINCDIR     := $(filter-out /usr/include, )

BUILDXML       := no
XMLLIBDIR      := 
XMLCLILIB      := LIBXML2_LIBRARIES-NOTFOUND
XMLINCDIR      := $(filter-out /usr/include, LIBXML2_INCLUDE_DIR-NOTFOUND)

HASXRD         := 
XRDINCDIR      := 
XRDLIBDIR      := 
EXTRA_XRDFLAGS := 
XRDVERSION     := 
HASXRDUTILS    := 
XRDINCPRIVATE  := 
BUILDNETXNG    := no
BUILDXPROOFD   := 
BUILDXRDCLT    := 

SRPLIBDIR      := 
SRPLIB         := 
SRPINCDIR      := $(filter-out /usr/include, )

BUILDSRPUTIL   := 
SRPUTILLIBDIR  := 
SRPUTILLIB     := 
SRPUTILINCDIR  := $(filter-out /usr/include, )

AFSLIB         := 
AFSLIBDIR      := 
AFSINCDIR      := 
AFSEXTRACFLAGS := 
AFSSHARED      := 

ALLOCLIB       := 
ALLOCLIBDIR    := 

BUILDKRB5      := no
KRB5LIB        := KRB5_LIBRARY-NOTFOUND
KRB5LIBDIR     := 
KRB5INCDIR     := $(filter-out /usr/include, KRB5_INCLUDE_DIR-NOTFOUND)
KRB5INIT       := KRB5_INIT-NOTFOUND

COMERRLIB      := 
COMERRLIBDIR   := 

RESOLVLIB      := 

CRYPTOLIB      := 
CRYPTOLIBDIR   := 

BUILDGLOBUS    := no
GLOBUSLIB      := 
GLOBUSLIBDIR   := 
GLOBUSINCDIR   := $(filter-out /usr/include, )

BUILDMONALISA  := no
MONALISALIBDIR := 
MONALISACLILIB := MONALISA_LIBRARY-NOTFOUND
MONALISAINCDIR := $(filter-out /usr/include, MONALISA_INCLUDE_DIR-NOTFOUND)

SSLLIB         := SSL_EAY_LIBRARY-NOTFOUND LIB_EAY_LIBRARY-NOTFOUND
SSLLIBDIR      := 
SSLINCDIR      := $(filter-out /usr/include, OPENSSL_INCLUDE_DIR-NOTFOUND)
SSLSHARED      := 

BUILTINLZMA    := 
LZMALIBDIR     := 
LZMACLILIB     := 
LZMAINCDIR     := $(filter-out /usr/include, )

SHADOWFLAGS    := no
SHADOWLIB      :=
SHADOWLIBDIR   :=

BUILDGENVECTOR := yes

BUILDMATHMORE  := yes
GSLFLAGS       := $(filter-out -I/usr/include, )
GSLLIBDIR      := 
GSLLIBS        := C:/external/vc12/gsl/1.16/lib/Release/gsl.lib C:/external/vc12/gsl/1.16/lib/Release/gslcblas.lib
GSLVERSION     := 

CINTMAXSTRUCT  := 
CINTMAXTYPEDEF := 
CINTLONGLINE   := 

BUILDCLING     := no
LLVMCONFIG     := 

BUILDCINTEX    := yes

BUILDREFLEX    := yes

BUILDROOFIT    := yes

BUILDMINUIT2   := yes

BUILDUNURAN    := yes

BUILDVC        := 
AVXCXXFLAG     := 
SIMDCXXFLAGS   :=  
VCFLAGS        :=  

BUILDVDT       := 

BUILDGDML      := yes

BUILDTABLE     := yes

BUILDTMVA      := yes

BUILDAFDSMGRD  := 
AFDSMGRDAPMON  := 

BUILDHTTP      := yes
USEFASCGI      := 
FASTCGIINCDIR  := 
ifeq ($(USEFASCGI), no)
FASTCGIFLAGS   := -DHTTP_WITHOUT_FASTCGI
endif

CPPUNIT        := 
GCCXML         := 

ROOTDICTTYPE   := cint

INSTALL        := cp -dpR
INSTALLDATA    := cp -dpR
INSTALLDIR     := mkdir -p
RSYNC          := rsync -au

ROOTDRPMREL    := 1
